openapi: "3.0.0"
info:
  description: "BoringAPI descripton for mining"
  version: "1.0.0"
  title: "BoringAPI"
servers:
  - url: http://127.0.0.1:19433

paths:
  /stats:
    get:
      tags:
      - "Stats"
      summary: "Get miner stats"
      responses:
        200:
          description: "Success"
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Statsreply"
        500:
          description: "Internal server error"

components:
  schemas:
    Statsreply:
      type: "object"
      properties:
        Algorithms:
          type: "array"
          items:
            type: object
            additionalProperties:
              oneOf:
              - $ref: "#/components/schemas/AlgoStats"
              - type: string
              - type: integer
            example:
              "CrypoNightV8":
                "CurrentPool": "xmr-eu1.nanopool.org:18888"
                "GPU 1":
                  "Accepted": 2
                  "Denied": 0
                  "Hashrate": "2.040000e+02"
                "GPU 3":
                  "Accepted": 4
                  "Denied": 0
                  "Hashrate": "1.990000e+02"
                "ReconnectionCount": 0
                "Total":
                  "Accepted": 6
                  "Denied": 0
                  "Hashrate": "4.030000e+02"
              "Ethash":0x8d8a54e4759eb24584a4d7455697aa1f51fb670f
                "CurrentPool": "etc-eu1.nanopool.org:19433"
                "GPU 0":
                  "Accepted": 3
                  "Denied": 0
                  "Hashrate": "2.040000e+07"
                "GPU 2":
                  "Accepted": 2
                  "Denied": 0
                  "Hashrate": "2.020000e+07"
                "GPU 4":
                  "Accepted": 5
                  "Denied": 0
                  "Hashrate": "1.970000e+07"
                "ReconnectionCount": 0
                "Total":
                  "Accepted": 10
                  "Denied": 0
                  "Hashrate": "6.030000e+07"
              "RandomHash":
                "CPU":
                  "Accepted": 6
                  "Denied": 6
                  "Hashrate": "1.980000e+02"
                "CurrentPool": "pasc-eu1.nanopool.org:19999"
                "ReconnectionCount": 0
                "Total":
                  "Accepted": 6
                  "Denied": 6
                  "Hashrate": "1.980000e+02"
        Devices:
          type: "array"
          items:
            additionalProperties:
              $ref: "#/components/schemas/DeviceStats"
            example:
              "CPU":
                "Name": "Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz"
                "Platform": "CPU"
              "GPU 0":
                "Name": "P106-100"
                "Platform": "CUDA"
                "Pci": "01:00.0"
                "Fan": 48
                "Temperature": 65
                "Power": 104.3
              "GPU 1":
                "Name": "RX 550"
                "Platform": "OpenCL"
                "Pci": "02:00.0"
                "Fan": 48
                "Temperature": 62
                "Power": 104.3
              "GPU 2":
                "Name": "P106-100"
                "Platform": "CUDA"
                "Pci": "03:00.0"
                "Fan": 48
                "Temperature": 62
                "Power": 104.3
              "GPU 3":
                "Name": "RX 550"
                "Platform": "OpenCL"
                "Pci": "04:00.0"
                "Fan": 48
                "Temperature": 59
                "Power": 104.3
              "GPU 4":
                "Name": "P106-100"
                "Platform": "CUDA"
                "Pci": "05:00.0"
                "Fan": 48
                "Temperature": 59
                "Power": 104.3
        WorkTime:
          type: "integer"
          example: 143
    AlgoStats:
      type: object
      properties:
        Accepted:
          type: integer
        Denied:
          type: integer
        Hashrate:
          type: string
    DeviceStats:
      type: object
      properties:
        Name:
          type: string
        Platform:
          type: string
        Pci:
          type: string
          description: Bus:Device.Function notation
        Fan:
          type: integer
        Temperature:
          type: integer
        Power:
          type: number
          format: double
